### ISSUE TITLE
VideoItem causes error using HTML5 controls

### ISSUE THREAD

**Issue by mopcweb** [MurhafSousli/ngx-gallery#323] opened 2020-03-11 17:38 UTC
Hi there!
Thanks for cool stuff. I just found some bug, info is under this msg:

#### What is the expected behavior?

Clicking on HTML5 video control menu I'm waiting for it to work correctly which is to open menu where i can choose among 2 options: download or play image in image

#### What is the current behavior?

If there is more than 2 videos in gallery on the page (even if there is this 3 videos in another copy of ngs-galley) clicking on menu control causing whole slides dissapear

#### What are the steps to reproduce?

Here is repro setup
https://stackblitz.com/edit/ngx-gallery-video-controls-error

#### What is the use-case or motivation for changing an existing behavior?

To use this package in Application

#### Which versions are you using for the following packages?

Angular: ~8.1.2
Angular CDK: ~8.2.3
Angular CLI: ~8.1.3
Typescript: ~3.4.3
Gallery: ^5.0.0-beta.0

Same w/ @ngx-gallery/core@^4.0.3

**Comment by mopcweb** [comment] 2020-03-11 18:20
Digging deeper found out that such behaviour is because of this css
```
transform: translate3d(0px, 0px, 0px);
```
on this element
```
<div class="g-slider" ng-reflect-ng-style="[object Object]" style="transform: translate3d(0px, 0px, 0px); width: calc(300%); height: 100%;">
...
</div
```

**Comment by MurhafSousli** [comment] 2020-08-08 23:42
I think it is the `overflow: hidden` which we use on gallery items wrappers

**Comment by MurhafSousli** [comment] 2022-12-14 04:13
I am not sure if this issue is still happening in ng-gallery@8.0.0, because the core was completely refactored. could you try it with the latest version? your reproduction link no longer works!

**Comment by MurhafSousli** [comment] 2023-01-21 09:23
I am considering this as fixed with version 8, if you were able to reproduce it, please open a new issue!

**Closed by MurhafSousli** 2023-01-21 09:23 UTC
Labels: bug, PRs are welcome, Help wanted
