### ISSUE TITLE
Lightbox bottom is out of screen on real mobile phones

### ISSUE THREAD

**Issue by kondi** [MurhafSousli/ngx-gallery#99] opened 2018-05-30 22:12 UTC
**Describe the bug**
Bottom part of the thumbnail images are out of screen.

iPhone 8:
![realios_iphone_8](https://user-images.githubusercontent.com/278688/40750161-a75e672e-6466-11e8-8892-78fc2709a3f6.jpg)

Nexus 6P:
![bs_realdroid_mobile_google nexus 6p-7 0-1080x1920](https://user-images.githubusercontent.com/278688/40750159-a3ebddce-6466-11e8-9781-bdee58f76ed8.jpg)

**To Reproduce**
1. Go to https://murhafsousli.github.io/ngx-gallery/#/lightbox
2. Click on any image

**Expected behavior**

It should look like this (chrome devtools with mobile view):

![image](https://user-images.githubusercontent.com/278688/40750259-fe242260-6466-11e8-90f7-29b58747f732.png)

**Which version are using? (please complete the following information):**
 - Package version v2.2.0
 - Angular version v6.0.3

**Comment by MurhafSousli** [comment] 2018-05-30 22:27
Duplicate of #86

@kondi There is no fix for this the normal way, [info](https://stackoverflow.com/a/37113430/1015648).

However now I am thinking of the use of `element.requestFullScreen();`

**Comment by kondi** [comment] 2018-05-30 22:42
Thanks for the info! The #66 complains about the close button, also it says it is working well on chrome. The close button is always there for me, but the cut bottom part is there on chrome and ios safari as well.

This simple means the lightbox gallery is not usable on mobile phone, so I think this should not be acceptable. Btw it was working well on 0.7.1, I don't think it was using element.requestFullScreen() at that time.

**Comment by MurhafSousli** [comment] 2018-05-30 22:59
@kondi I am confused! I don't remember anything about 0.7.1.

The lightbox works well on chrome. but Safari simply won't allow us to cover its bottom bar. 
maybe we can fix this by detecting the browser, adding a `.lightbox-safari` class and adjust it with CSS. however, we still need to calculate that bar's height

Also, Safari does not support the fullscreen API https://caniuse.com/#feat=fullscreen

**Comment by kondi** [comment] 2018-05-30 23:05
You can see 0.7.1 in action at: https://www.joliroom.com/fr/results/Paris,%20France/2018-06-07/2018-06-08/1-2-0/home/details/home-1184414475-414?searchId=54430959 You have to wait till the search is finished, then click on the main big picture on top. It had other usability issues (top part is transparent behind the close button and sliding animation is silly), but not this bug.

**Comment by kondi** [comment] 2018-05-30 23:07
In this bug report, you can see the screenshot made with a clean Chrome on Android, only the top part of thumnbails are visible with the latest version of ngx-gallery.

**Comment by MurhafSousli** [comment] 2018-05-30 23:32
I just compared the current `gallery.scss` and `lightbox.scss` with the ones in 0.7.1, and they look identical.
in both versions, the plugin uses the CDK overlay. It could be an update in the CDK that caused this behavior but I cannot tell what went wrong!

**Comment by MurhafSousli** [comment] 2018-05-30 23:49
I figured it out!
```scss
lightbox {
    position: fixed;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    height: 100% !important;
}
```

**Closed** 2018-05-31 00:03 UTC
Labels: bug

**Comment by kondi** [comment] 2018-05-31 08:30
Thanks, it works perfectly now!
