### ISSUE TITLE
use Base64 URLs as source 

### ISSUE THREAD

**Issue by Ingeborg87** [MurhafSousli/ngx-gallery#365] opened 2020-10-28 15:50 UTC
Hi, 

i want to read an image that is selected via directory and later on, send the image to a backend. This view shall be extendable in the future, that's why i need a viewer, that can handle different sized images. The ngx-gallery is fulfilling this needs but it seems that there are some issues with showing base64 URL data. 

The implementation was rather quick but the screenelement is only black. 

I initiated everything here:

**app.component.ts**
```
ngOnInit() {
    this.galleryItems = new Array<GalleryItem>();
    this.galleryRef = this.gallery.ref('lightbox');
    this.galleryRef.setConfig({
        imageSize: ImageSize.Cover,
        thumb: false,
        itemTemplate: this.itemTemplate,
        gestures: false
    });
}
onClickFileInputButton(): void {
    this.fileInput.nativeElement.click();
}
onChangeFileInput(): void {
    const files: { [key: string]: File } = this.fileInput.nativeElement.files; // load the chosen file
    this.file = files[0];
    const reader = new FileReader();
    reader.readAsDataURL(this.file); // read the Base64 string
    reader.onload = event => { // when loaded
        this.url = this.domSanitizer.bypassSecurityTrustUrl(event.target.result.toString()); // do some sanitizing stuff
        this.galleryItems = new Array<GalleryItemComponent>();
        this.galleryItems = [{
            data: {
                src: this.url
            }
        }];
        this.lightboxRef.load(this.galleryItems);
    };
}
```

**app.component.html**
``` ts
<div fxFlex fxLayout="column" fxFlexFill *ngIf="galleryItems.length > 0">
        <gallery fxFlex="70%"
          class="buttonNewPicture"
          [items]="galleryItems"
          [itemTemplate]="itemTemplate"
          [gestures]="false"
          [thumb]="false"
          [counter]="false"></gallery>
</div>
 <div fxFlex="50%" fxLayout="row" fxLayoutAlign="start center" fxFlexFill>
    <input type="file" style="display: none" #fileInput accept="image/*" (change)="onChangeFileInput()" />
    <button mat-raised-button
        color="primary"
        class="marginLeft20px buttonNewPicture"
        (click)="onClickFileInputButton()">
        <mat-icon>attach_file</mat-icon>
        Neues Bild
    </button>
    <button
        *ngIf="galleryItems.length > 0"
        mat-raised-button
        color="primary"
        class="buttonNewPicture"
        (click)="lightbox.open(0, 'lightbox', {panelClass: 'fullscreen'})">
        <mat-icon>open_in_full</mat-icon>
    </button>
</div>
```

Sadly there is no error or anything to show. I can use the fullscreen mode (which is still just black). The counter on top of lighthouse is recognizing an existing galleryitem but that's it. Sadly i have no further error messages or something else to show cuz there are nowhere popping up any. 

Thx

Edit:
Here is the Inspector output from Firefox
![grafik](https://user-images.githubusercontent.com/7937005/97463831-749d4f80-1940-11eb-85fc-7ee89a4604f3.png)

**Comment by MurhafSousli** [comment] 2021-02-17 19:26
Sorry, I cannot look into the issue since it does not follow the issue template, please provide a stackblitz reproduction when you open a new one so I can look into it. closing for now..

**Closed by MurhafSousli** 2021-02-17 19:26 UTC

**Comment by Fribb** [comment] 2022-04-28 07:38
Just to give a possible solution to the posted problem even though this issue is a bit old.

```
      const reader = new FileReader();
      reader.onload = event => {
        this.images = new Array<GalleryItemComponent>();
        let image = new ImageItem({ src: event.target?.result as string});
        this.images.push(image);
      };
      reader.readAsDataURL(file);
```
