### ISSUE TITLE
The lightbox doesn't work on the demo and on my application

### ISSUE THREAD

**Issue by GitHubish** [MurhafSousli/ngx-gallery#375] opened 2021-01-14 13:46 UTC
I noticed that on the [demo](https://ngx-gallery.netlify.app/#/lightbox) the lighbox doesn't work, when I open it there is just a black background and the image is not displayed. So I did a test project and I have exactly the same problem. There is no error in the console. 

![2021-01-14_14-43-14](https://user-images.githubusercontent.com/7701833/104598552-ff0b6a80-5676-11eb-99dc-efb88fb591dc.gif)

Do you know where this problem comes from?
Thanks

**Comment by MurhafSousli** [comment] 2021-01-14 16:11
Yea I need to redeploy the demo but there is nothing wrong with the library, it is working the stacbklitz

duplicate of #370

**Closed by MurhafSousli** 2021-01-14 16:11 UTC

**Comment by GitHubish** [comment] 2021-01-15 10:09
Thank you, I see where it didn't work. The stackblitz is a good example! I suggest that the demo be available online unless it's already the case.
