### ISSUE TITLE
Lightbox Gestures not working in mobile phones

### ISSUE THREAD

**Issue by VISHNUCR1994** [MurhafSousli/ngx-gallery#280] opened 2019-04-25 09:30 UTC
#### What is the expected behavior?
In mobile phones such as Android and IOS,gestures for lightbox wants to work.

#### What is the current behavior?
Gestures is not working properly! Sometimes If hardly swipes, it rarely works(Also installed `hammer.js` & tried `panSensitivity` in your API)
#250 Like this issue in his youtube video.

**Comment by MurhafSousli** [comment] 2019-04-26 00:19
As you see, I closed that issue because it has no details or reproduction, playing a video is not helpful since I don't see how it is being used, it could be a problem his code!

The lightbox gestures works properly, try this [stackblitz](https://stackblitz.com/edit/ngx-gallery)

If you still have the issue, reproduce it with a stackblitz and I will look into it asap

**Comment by VISHNUCR1994** [comment] 2019-04-26 06:21
Hello @MurhafSousli .Yeah! I know why you closed the issue and also i already tried the stackblitz example in many mobiles,In `ngx-gallery` the swipe works fine and in `Lightbox` the swipe is little hard,this is my problem,i want smooth scrolling with lightbox,Is that possible and also why the `panSensitivity` is used for?

**Comment by jaydeep9rl** [comment] 2020-02-18 22:36
I am experiencing the same gestures issue even with stackblitz on iOS 13.x.x.
I tried to use the same version in package.json as stackbltiz and it does not work.

```
**stackblitz - package version:**
"@angular/cdk": "^7.1.1",
"@ngx-gallery/core": "^4.0.1",
"@ngx-gallery/lightbox": "^4.0.1",
"hammerjs": "^2.0.8",

**Latest - package version.**
"@angular/cdk": "^8.2.3",
"@ngx-gallery/core": "^5.0.0-beta.0",
"@ngx-gallery/lightbox": "^5.0.0-beta.0",
"hammerjs": "^2.0.8",
```

it seems like hammer js is not working properly. any help is appreciated!

**Comment by bdonnellysurge** [comment] 2020-04-09 23:17
In the stackblitz above if you make it full screen swipe gesture is broken in firefox and chrome on desktop: https://ngx-gallery.stackblitz.io/ It's something to do with browser window width since it works when you shrink the browser window.

**Comment by lgaida** [comment] 2021-05-04 09:35
I'm also experiencing problems with gesture support but can not reproduce the issue in a simple stackblitz.
Swiping behaves similar to the video posted in #250 
I'm also getting violation logs inside Chrome-DevTools when using multiple galleries (with multiple images) on a page.
The more galleries i use the higher the violation in ms gets
```
[Violation] 'pointermove' handler took 216ms zone-evergreen.js:1611
[Violation] 'pointerup' handler took 221ms zone-evergreen.js:1611
[Violation] 'pointermove' handler took 222ms zone-evergreen.js:1611
[Violation] 'pointermove' handler took 211ms zone-evergreen.js:1611
[Violation] 'pointermove' handler took 214ms zone-evergreen.js:1611
```
After removing hammerjs from my dependencies and polyfill everything works fine (except for gestures of course)

**Comment by lgaida** [comment] 2021-05-04 13:58
I was able to get rid of the violation warnings by using `changeDetection: ChangeDetectionStrategy.OnPush`.
I also noticed that swiping works for chrome mobile but not for firefox mobile.

**Comment by jginorio** [comment] 2021-05-15 21:36
In case you guys still have the problem I'm using Angular 10.2.4 with @ngx-gallery/core & @ngx-gallery-input both on v4.0.1 and hammerjs v2.4.0. I solve the problem by importing(import 'hammerjs') to the 'pollyfills.ts' file

**Comment by APoska** [comment] 2021-09-06 12:06
I had the same issue and I noticed it works when sliding with two fingers

**Comment by MurhafSousli** [comment] 2022-08-27 04:53
Try v7.0.2, if the issue still occurs, please open a new issue, closing this for now...

**Closed by MurhafSousli** 2022-08-27 04:53 UTC
Labels: need: reproduction
