### ISSUE TITLE
After using Angular 7.2.3, the gallery images wouldn't show

### ISSUE THREAD

**Issue by jasperltz93** [MurhafSousli/ngx-gallery#269] opened 2019-02-05 06:06 UTC
![image](https://user-images.githubusercontent.com/26257150/52255709-85c55200-294e-11e9-887a-1c669dac30a5.png)
This is the issue, the images wouldn't load and the loading bar is on top left instead of middle, this happen when I scroll though all the images, then on the second lap, all images wouldn't load

`"dependencies": {
    "@angular/animations": "^7.2.3",
    "@angular/cdk": "^7.3.0",
    "@angular/common": "^7.2.3",
    "@angular/compiler": "^7.2.3",
    "@angular/core": "^7.2.3",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "^7.2.3",
    "@angular/http": "^7.2.3",
    "@angular/material": "^7.3.0",
    "@angular/platform-browser": "^7.2.3",
    "@angular/platform-browser-dynamic": "^7.2.3",
    "@angular/router": "^7.2.3",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-brands-svg-icons": "^5.3.1",
    "@fortawesome/free-solid-svg-icons": "^5.3.1",
    "@ngx-progressbar/core": "^5.3.1",
    "@ngx-progressbar/http": "^5.3.1",
    "@ngx-progressbar/router": "^5.3.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "highlight.js": "^9.13.1",
    "ngx-highlightjs": "^3.0.1",
    "ngx-scrollbar": "^4.1.1",
    "rxjs": "^6.3.3",
    "zone.js": "^0.8.27"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.0",
    "@angular-devkit/build-ng-packagr": "^0.13.0",
    "@angular/cli": "7.3.0",
    "@angular/compiler-cli": "^7.2.3",
    "@angular/language-service": "^7.2.3",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.9.4",
    "ansi-colors": "^3.0.5",
    "codelyzer": "~4.4.4",
    "jasmine-core": "~3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.3",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.3.1",
    "ng-packagr": "^4.6.0",
    "protractor": "~5.4.0",
    "replace-ext": "^1.0.0",
    "ts-node": "~5.0.1",
    "tsickle": "^0.34.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "^3.2.2"
  }`
The version i'm using

**Comment by hajdun** [comment] 2019-02-06 15:00
Good for you, for me it would not even build.  ERROR in node_modules/@ngx-gallery/lightbox/lib/lightbox.animation.d.ts(1,47): error TS1005: ',' expected.

**Comment by jasperltz93** [comment] 2019-02-06 17:34
I'm using master branch, after I change the angular library to latest version as with the question above, then the command I used is:
1. npm install
2. npm run init-build
3. npm run start-demo

**Comment by astr0sl0th** [comment] 2019-02-07 18:56
I can confirm I am experiencing the same issues too on Angular 7.2.3

**Comment by falharbi88** [comment] 2019-02-09 17:02
I am facing the same issue saying Unable to load the image

**Comment by maertz** [comment] 2019-02-10 18:16
I had the same issue with Angular 7.0.3, in my case it helped to change the loading mode to "intermediate".

**Comment by falharbi88** [comment] 2019-02-10 18:21
@mertz Would you please explain how can I do that?

**Comment by maertz** [comment] 2019-02-10 21:20
Sure, take a look to the config API, you just need to overwrite the default like so:

```
const config: GalleryConfig = {
  loadingMode: "indeterminate"
};
galleryRef.setConfig(config)
```

https://github.com/MurhafSousli/ngx-gallery/wiki/Gallery-API#gallery-config-api

**Comment by halilkalkan** [comment] 2019-02-16 21:54
> I had the same issue with Angular 7.0.3, in my case it helped to change the loading mode to "intermediate".

Wow, thank you Maertz, I've been trying to solve this issue and it works like a charm ! :)

**Comment by andy200486** [comment] 2019-03-01 15:48
I'm not sure if I'm facing the same problem but I can figure out that when I use : 
`addImage` then `remove` and then `addImage` the gallery doesn't show any image anymore. I've set loadingMode to indeterminate but it doesn't work for me

**Comment by jonandresl** [comment] 2019-03-13 14:34
@maertz Where in the code do you overwrite the default? Sorry if this is a dumb question, I'm new to Angular aswell as this gallery. 
Thank you!

**Comment by jersonjcnt** [comment] 2019-03-17 00:32
I also have the same problem. Angular 7.2.0

**Comment by MurhafSousli** [comment] 2019-03-17 02:58
@andy200486 @jasperltz93 here you go https://material.angular.io/cdk/overlay/overview

Just add this line in your global style

```css
@import '~@angular/cdk/overlay-prebuilt.css';
```

**Comment by jersonjcnt** [comment] 2019-03-17 03:42
I think I find an alternative solution for all current problems.

reference code. [https://stackblitz.com/edit/ngx-gallery-imageviewer](https://stackblitz.com/edit/ngx-gallery-imageviewer)
**home.compoment.html**
` <button color="accent" (click)="openLightBox(1)">Open Lightbox in fullscreen mode</button>
              <ng-template 
              #itemTemplate 
              let-index="index" 
              let-type="type" 
              let-data="data" 
              let-currIndex="currIndex">
            <ng-container *ngIf="type === 'imageViewer' && index === currIndex">
              <ngx-imageviewer [src]="data.src"></ngx-imageviewer>
            </ng-container>
          </ng-template>`

**home.component.ts**
`  openLightBox(idItem: number) {
    const lightboxRef = this.gallery.ref('lightbox');

    lightboxRef.setConfig({
      thumbPosition: ThumbnailsPosition.Top,
      itemTemplate: this.itemTemplate,
      gestures: false,
      imageSize: 'cover',
      loadingMode: 'determinate', 
      loadingIcon: 'Loading...'
    });

    this.lightbox.open(idItem, 'lightbox', {panelClass: 'fullscreen'})
  }`


start the component again by clicking on a button or image.

**Comment by MurhafSousli** [comment] 2019-06-04 01:28
There seem to be a bug with loading the images using the default progressive image loader (using HttpClient and BLOB URL), I think it is better to deprecate it in the next version, for now you can stick to the `intermediate` mode

**Comment by Mertz** [comment] 2019-06-04 05:12
oi ding dongs wrong email me stop emailing me
-different mertz
    On Monday, June 3, 2019, 6:29:00 PM PDT, Murhaf Sousli <notifications@github.com> wrote:  
 
 
There seem to be a bug with loading the images using the default progressive image loader (using HttpClient and BLOB URL), I think it is better to deprecate it in the next version, for now you can stick to the intermediate mode

**Comment by chiragms** [comment] 2019-07-02 05:17
@maertz Man you are a life saver! I've been trying to solve this since past couple of hours and your comment was like a light in the dark!!
Saved my whole day!! Thanks a million... cheers.. 🖖

**Comment by playkang** [comment] 2019-07-03 08:29
@maertz Thank you!!! You made my day!

**Comment by DePalmo** [comment] 2019-11-14 21:44
@maertz Your solution works, thanks!

But the issue still persists if we use `loadingMode: determinate`, images do not load on second view. In my case, the images do load the first time but if I close the lightbox and open it right after, it only shows an empty loader and no images.

```"@angular/core": "~8.0.3",
"@angular/material": "~8.0.1",
"@angular/service-worker": "^8.0.0",
"@ngx-gallery/core": "^4.0.3",
"@ngx-gallery/lightbox": "^4.0.3"``

**Comment by DePalmo** [comment] 2019-11-14 21:45
Oh, the linked documentation is wrong: https://github.com/MurhafSousli/ngx-gallery/wiki/Gallery-API#gallery-config-api

It says to use
```
GalleryModule.forRoot({
  loop: true
})
```

but the `GalleryModule` does not have a `.forRoot()` option, it does `.withConfig()`.

**Comment by MurhafSousli** [comment] 2020-03-14 14:56
Closing this since the `determinate` loading mode is been deprecated in the recent version.

**Closed by MurhafSousli** 2020-03-14 14:56 UTC
Labels: bug
